services:
  gazebo-sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: gazebo-harmonic-sim
    container_name: gazebo-sim
    runtime: nvidia

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - GZ_SIM_RESOURCE_PATH=/workspace/models:/workspace/worlds
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/workspace:rw
      - ./workspace/.gz:/root/.gz:rw

    network_mode: host
    stdin_open: true
    tty: true
    working_dir: /workspace
